behaviors:
  CoinAgent:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    hyperparameters:
      batch_size: 64
      buffer_size: 1200
      learning_rate: 3.0e-4
    network_settings:
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
